spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/mydb
    username: root
    password: '{cipher}AQAoRjLnWjjwaUQWfkNawPXLOcUnYa7iBOn0+i4ZXoI75amYdsB0v9nUVX3ywScMP4WLA8WFDS82w61nZLAaIqUXmX5q5i1rNGuiDU61THtI9dWLGbme1M/NxoqF/2oz8x2t4MwDPUz+4D/gDuzxPPLCXiCQ2cEAXwlNf5PodAxx0T5F9k+IqNLD+vIDTiXdmdbWeItmHYkN4I/pmnzYOHeaZWlypdgHPGJiv/t5rdYiz8vJI04KW1Y30G5Acpj/Ne6TdSr9/6nVh7nyoY93vbhI7bxztlEJ7VW4aSJ+twLQnBq68YYMh5qdGQyBucUBO30P0lJWZohsJ/ZKkpiNN3FLMM4NRYKc08jMGJX0MTw5MVQLRmaNlgkEX9FN/rbUsyE='
  # datasource:
    # driver-class-name: org.h2.Driver
    # url: jdbc:h2:mem:testdb
    # username: sa
    # password: '{cipher}AQAG/7o/i0N0ERzVe6eW3qOf+dlRy4pKXDTXZQjXL2mbqvY0V/UjRnX35OrOlyDY+6rGelCVCjLA6DSKimH7q+l2w7UC/kBPSCa2WPI6jm1rufpC7Vw8iCtwP8BVNTczQwBNpIlyHQjUj8/6lsDWdqmNQUAoOKHfPMR4qHEWbRiCi8PREOH9UMJ7UIn1LqVlBdfKkfwxaaZ61knxVEnj+vMNvtLBjuKFFJCwbMxXkBdqts/o8RGxny60mjhiSL6fZrgLYcScM5k++SHQir5qICKYH7iAyiTbfIpZS1kDi0GrR/q/Bf7Xufc2HV/mCrnAHj5IBx0a9QTmwzCSQFo7V9WEnuBIJLLHX1kH5SrvwsUITiIp3S1zicBf5R5iqVcHY0c='

order-service:
  # url: http://127.0.0.1/ORDER-SERVICE/%s/orders
  url: http://ORDER-SERVICE/%s/orders
  exception:
    orders-is-empty: 'There is no items'
